### ISSUE TITLE
Forums DB is still being used

### ISSUE THREAD

**Issue by JarnoVgr** [MrGreenGaming/MTA-Resources#103]
It looks like 'gcshop\teams\teams_s.lua' still uses the forums database around line 39/40. I think this needs to be removed/fixed/whatever

**Comment by EsDeKa** [comment]
Do you mean the foreign keys in the table creation? If so it was just something I was experimenting with and can be removed easily

https://github.com/JarnoVgr/Mr.Green-MTA-Resources/blob/master/resources/%5Bgameplay%5D/gcshop/teams/teams_s.lua#L22
https://github.com/JarnoVgr/Mr.Green-MTA-Resources/blob/master/resources/%5Bgameplay%5D/gcshop/teams/teams_s.lua#L33

**Comment by EsDeKa** [comment]
@JarnoVgr status?
