### ISSUE TITLE
(NFS) Nitro unusable if not full sometimes

### ISSUE THREAD

**Issue by Megas97** [MrGreenGaming/MTA-Resources#142]
Pretty much what the title says. Sometimes I can't use nitro unless it's on 100%. MTA restart fixes but yeah...rip race. Idk if others have that problem too.

**Comment by EsDeKa** [comment]
Restart mta or reconnect

**Comment by AleksCore** [comment]
I usually restart race_fix resource when it happens and it helps for all players.

**Comment by Megas97** [comment]
Yea i know how to fix it by restarting ;p still better if you can perma fix it tho :)

**Comment by AleksCore** [comment]
There was an opinion that this bug happens after maps with coremarkers. Possibly fixed in f9fbdd5e48253e7694ff9ace513eeb54d3c06b58

**Comment by Megas97** [comment]
Just had it again today  though :(

**Comment by AleksCore** [comment]
Still happens?

**Comment by Megas97** [comment]
Markers still disabled :D so idk. Hasn't happened while they were off.

**Comment by AleksCore** [comment]
Let's hope it fixed. I noticed that the only thing which connects coremarkers and nitro is the same binds. Also wiki.mtasa.com [say](https://wiki.multitheftauto.com/wiki/UnbindKey):  If you do not specify handler, any instances of key being bound will be unbound, whatever function they are bound to.
