### ISSUE TITLE
Merge GC login and MTA login

### ISSUE THREAD

**Issue by GingerAdonis** [MrGreenGaming/MTA-Resources#147]
Makes not much sense to have 2 separate account systems. Is there a reason not to merge them?

**Comment by EsDeKa** [comment]
Well it would be a lot of work, current acl system is very extensive and many resources use it
It would be nice but is pretty low priority imo

**Comment by JarnoVgr** [comment]
Linking them is fine with me. Just don't want normal users to register for both. If only admins gotta do it then not linking them is fine as well. (Linking would still be a nice feature though)

**Comment by Nick026** [comment]
For security reasons this should be kept seperated. If for some reason our forums isn't reachable all admin access will be lost
