### ISSUE TITLE
/like binds in maps are skewing ratings

### ISSUE THREAD

**Issue by EsDeKa** [MrGreenGaming/MTA-Resources#167]
Related to #45

Idea: use [unbindKey(+, like)](https://wiki.multitheftauto.com/wiki/UnbindKey) at the start of every map (or on a timer for all I care). Not sure that works though

**Comment by AleksCore** [comment]
@EsDeKa nice idea. I can unbind all keys bound to "like" and "dislike" commands at the start of every map, but what if some players binded it to easy like/dislike maps? They'll lose their binds.

**Comment by EsDeKa** [comment]
You can't unbind those I think, I'm not sure you can even unbind binds from other resources, needs some testing

**Comment by AleksCore** [comment]
@EsDeKa wiki: unbindKey will only work on binds that were added by the same resource

**Comment by EsDeKa** [comment]
Then the only solution I see is moving it to GUI for now until we have some kind of ACL

**Comment by Flipper123** [comment]
for all new maps, map manager can check if like is binded to + while testing map, and if yes he can deny it

**Comment by EsDeKa** [comment]
New idea: from 1.5.2 on you can use https://wiki.multitheftauto.com/wiki/AddDebugHook to skip functions, looks like it might be doable with this
