### ISSUE TITLE
team bug in tab

### ISSUE THREAD

**Issue by Flipper123** [MrGreenGaming/MTA-Resources#168]
u can see few teams are empty atm, and they stay in tab, can that be fixed? So they wont be in tab when they are empty
![image](https://cloud.githubusercontent.com/assets/16647544/13587176/9690cef4-e4c6-11e5-972b-532a77731c9a.png)

**Comment by EsDeKa** [comment]
@AleksCore Could your recent changes with scoreboard have anything to do with this?

**Comment by AleksCore** [comment]
@EsDeKa I don't think so and also I don't like this teams in scoreboard. 

Without teams scoreboard looks much better and sorting works correctly.

![screenshot](http://i.imgur.com/Hd8X4FI.jpg)

**Comment by AleksCore** [comment]
Maybe add another column right after voice column to show team short name? Sort by team - PROFIT. It's a nice solution imo and scoreboard will be clear

**Comment by AleksCore** [comment]
@EsDeKa can you look into this issue, please?

**Comment by EsDeKa** [comment]
I think I had fixed it already, does it still happen @Flipper123

**Comment by Megas97** [comment]
Confirm, MIX is full of empty teams.

**Comment by BobT123** [comment]
it would look better if it could be in name's column and only way to use clan tag to be joined in team, also it should remove tag from those who aren't in team imo.

**Comment by BobT123** [comment]
btw it's typical for original team resource, it fails to refresh.

**Comment by Nick026** [comment]
Fixed by checking for empty teams during map switch
https://github.com/MrGreenGaming/MTA-Resources/commit/96b5d17c51763c954e0ff9eec7ed07359c1282da
