### ISSUE TITLE
Move textual speed meter to bottomleft

### ISSUE THREAD

**Issue by JarnoVgr** [MrGreenGaming/MTA-Resources#17]
When using the new HUD the textual speed meter is still at the top-right, while the speedbar is at the bottom-left. Maybe move it?

**Comment by AleksCore** [comment]
ehh better to leave it as it is IMO. But change color from blue to white

**Comment by JarnoVgr** [comment]
Care to elaborate? 
Op 9 okt. 2015 8:13 PM schreef Aleksey <notifications@github.com>:ehh better to leave it as it is IMO. But change color from blue to white

**Comment by AleksCore** [comment]
Oh I got it wrong, sorry. I use old HUD and for me speedbar is at the top right. For old hud better to leave it as it is and for new HUD idk because I don't use it and not going to use.

**Comment by EsDeKa** [comment]
Is this what you meant @JarnoVgr ?
https://github.com/AleksCore/Mr.Green-MTA-Resources/commit/e3b1c78ba6f082685fef142ce24710a98b0a7bde

**Comment by AleksCore** [comment]
This is what Ywa talking about. http://i.imgur.com/DaI7jNg.png 

But idk where we should move it.

**Comment by JarnoVgr** [comment]
Well I suggest to move the text display (only for new HUD) inside the radar, like how the clock is placed.
