### ISSUE TITLE
Improve intermission screen

### ISSUE THREAD

**Issue by JarnoVgr** [MrGreenGaming/MTA-Resources#170]
The map voting screen has been improved recently. But I think the screen can be improved even more.
- Vote between more maps. 6 maybe?
- Show details of maps, such as:
  - Type of race ('Drag race', 'Single checkpoint', 'Laps', 'Fun' etc.)
  - Thumbnail would be nice, but that would be a lot of work.
  - Amount of likes and dislikes
- Make new maps & very high-rated stand out from the other maps during voting.

While the vote screen is shown, it would also be nice to show details about the finished race. Personal stats, and race stats. Who finished first, best newcomer etc.
This would be a great addition to make players feel better of themselves and for regulars to make sure they do their best so their name is shown on-screen.

Thoughts?

**Comment by Megas97** [comment]
I personally think the "Next Map" or "Play Again" thing is one of the best things on the server. This way everyone knows that it's either same map again or the next one. If more votes come it'll be kinda confusing and you can't know which map it'll be for sure. Amount of likes is seen in the next map window at upper right corner so idk why put in voter as well. Other stuff sounds needed tho, like the type of race for example (although idk how you'll make that, checking almost 2k maps and doing it manually seems bad and I can't think of another way to check if race is drag or circuit :D).

**Comment by JarnoVgr** [comment]
Doing that manually is the only way I assume yes.

Showing rating (likes/dislikes) it in the vote screen allows an easier choice between the 2 (or more) options.

What about doing 2 votes? 1 for 'New map' or 'Replay', and second vote (only if 'new map' has been chosen) which allows a vote on 6 maps.

I presume it would also stimulate map creators because they at least see their map name passing by more often. En maybe they can ask their friends to vote more often on it. etc.

**Comment by Megas97** [comment]
OK, I agree on the likes/dislikes thing, but I ust love having 2 options so that sounds bad to me :) Let's see what others say tho, it is your server after all so final decision is made by you, sdk and maybe aleks and kali.

**Comment by AleksCore** [comment]
I like this idea, especially about race stats and personal stats. I'll keep it in mind and see what I can do. Soon (c)

**Comment by JarnoVgr** [comment]
It would also be nice to see what people vote. So that it shows how many people have voted for it already.
