### ISSUE TITLE
Perk Suggestion

### ISSUE THREAD

**Issue by f1madkiller** [MrGreenGaming/MTA-Resources#191]
How about for all cars but Monster truck (good reason for this) Hydrolics, make it 5k GCs for the perk maybe?

**Comment by Megas97** [comment]
+1

**Comment by AleksCore** [comment]
I don't know why anyone need hydraulics at all :D But, well, yeah, hydraulics it's fun, especially on the mix server. I want to see more opinions about this suggestion. And if we'll want to make it, how it should work? You buy perk and enable/disable hydraulics by pressing the button in GC shop and it will be affected on the all cars except monster etc?

**Comment by f1madkiller** [comment]
buy merk and you can add hydrolics to each car like you do with PJ all but the monster truck as with monster you add it you can't control it as the wheels go up to the body
