### ISSUE TITLE
Clans

### ISSUE THREAD

**Issue by f1madkiller** [MrGreenGaming/MTA-Resources#192]
Can we have after 120 days a expired clan is removed from F6 as we got like 100 clans more than half are non excistant any more, it would tidy the list up + clans with no owners can be removed aswell maybe?

**Comment by f1madkiller** [comment]
@Bierbuikje

**Comment by Bierbuikje** [comment]
I don't think clans that expired should be removed, maybe the leader wants to open it again and he should have that option without the hassle of inviting all members again. But the clans without members or without a leaderr should be removed I think.

**Comment by f1madkiller** [comment]
Ye or if a clan expired lets say 2 years then it can be delted imo but best wait for Ywa and SDKs oppinon on this one Bier
