### ISSUE TITLE
VIP system suggestion

### ISSUE THREAD

**Issue by BobT123** [MrGreenGaming/MTA-Resources#194]
i've been thinking about it quite some time now, i think we should have it because some players rather earn gc than buy it so we should have some attractive system that makes player willing to pay, it won't be pay to win, it should give advantages over normal membership so let's say it will cost 14.99$ or 9.99$ month.

what should player get for vip membership?

free map purchase in every hours
free activation of any perk max 5 perk (until his have vip activated).
monthly bonus 5k gc with rising 100 gc in every month up to end of year as bonus of not canceling membership,
free access to horns (vip can set any horn which he wants to use) but in case of canceling membership he will lost access to those horns,
access to animated paintjobs exclusive for vip
more wheel skins exclusive for vip,
vip vote should have more value than normal members, like vip vote =5 player, normal=1
(maybe) ability to transfer gc exclusive of vip
special status on forum.
and there could be other good ideas, imo it will improve server revenues and help to improve it more if needed.

**Comment by f1madkiller** [comment]
Does sound a good idea @JarnoVgr would be the best one too pitch this too as it would help Ywas funds if not help Ywa invest into devolping the servers more

**Comment by Megas97** [comment]
Nice idea, Bob. But GC transfer should be there for everybody :)

**Comment by AfuSensi** [comment]
VIP has been added!
