### ISSUE TITLE
Multi-language chat

### ISSUE THREAD

**Issue by AleksCore** [MrGreenGaming/MTA-Resources#20]
I don't really like this but we need it tho. I remember we had multi-chat but it was reverted for some reason.

Also need options for client to remove IRC chat, system messages, etc

**Comment by JarnoVgr** [comment]
Yes we need this. Also a multi-lingual server (resources) would come in very handy to make this server more interesting for foreigners.

**Comment by AleksCore** [comment]
I thought about this. It shouldn't be hard to do multi-lang. But I can translate only to russian :D

**Comment by AleksCore** [comment]
I have started to translate shop (F6) by the way.

**Comment by EsDeKa** [comment]
We tried that 3 times iirc (me, bin, kali)
Most people ignored it or didn't know about it, so we'd have to force it with the admins this time

**Comment by JarnoVgr** [comment]
Now I don't want to copy everything that other servers have. But FFS has a language selection dialog when joining the server. And maybe make a extra checkbox if people want to participate in the global chat?

**Comment by EsDeKa** [comment]
We'll wait for Kali to come back for his chat resource, his was the best version I believe

For the translations I made a separate issue #21 since it's a lot more work

**Comment by JarnoVgr** [comment]
Could someone look into this? I see no reason not to implement this.

**Comment by AfuSensi** [comment]
My old resource still has tables in the database, we could reintroduce that. But last time we did that it started a riot.
