### ISSUE TITLE
Horns while not "alive"

### ISSUE THREAD

**Issue by Megas97** [MrGreenGaming/MTA-Resources#204]
Right now horns are heard only if players are in "alive" state. Would be better if they're heard while "spectating" and "away" as well.  

Example:
Now: I'm alive and @AleksCore is spectating me. I press RMB but he doesn't hear titten.
Should be: I'm alive and @AleksCore is spectating me. I press RMB but this time he does hear titten ;)

**Comment by Megas97** [comment]
Same with the chat bubble btw^

**Comment by AleksCore** [comment]
Weird, I hear horns while spectating. About chat and horn icons - I dont know how to do it and why it works like this. Guess @EsDeKa knows more about this

**Comment by AleksCore** [comment]
Well, seems like it doesn't work because vehicles "physically" in the air while spectating. Still don't know any good and easy solution for this.

**Comment by Megas97** [comment]
@AleksCore you did something? Because I think I saw/heard a horn while I was spectating a player :D

**Comment by AleksCore** [comment]
@Megas97 did nothing, except restart gcshop

**Comment by Megas97** [comment]
Nvm, the guy was close to me when I hit B so horn was heard. My bad :)
