### ISSUE TITLE
Improve new F2 GUI

### ISSUE THREAD

**Issue by AleksCore** [MrGreenGaming/MTA-Resources#205]
We've got [new menu](https://github.com/JarnoVgr/Mr.Green-MTA-Resources/commit/66b97dcf7ff1300eb34f1c35982aad8e3da4f9ca) and now its time to improve it. 
- show current map name and round
- ...
- ...

**Comment by JarnoVgr** [comment]
- Add short server descriptions. For example: 'Mix' doesn't really specify what it is about. The screenshot makes it more clear, but it could be improved.
- Maybe add a list of online playernames?
- Add option to join server when the next round/map starts.

**Comment by Megas97** [comment]
- when you're in race or mix and click the icon in F2, should get rid of the gui window. Now you have to click F2 again to remove it, clicking above the "You are here" text doesn't do it.

**Comment by Megas97** [comment]
Today the info in F2 was stuck at a map which has passed mins before I opened the GUI. Another map started but map name and author in F2 were on the old map, first time this happened.
