### ISSUE TITLE
Save for all cars - Modshop

### ISSUE THREAD

**Issue by Flipper123** [MrGreenGaming/MTA-Resources#211]
We can add new buttons in f6-modshop, in Colors+Paintjobs and in Rims+Upgrades, 
In Colors+Paintjobs- button for removing Paintjob from all cars
In Rims+Upgrades - button for setting same Wheels on all cars

**Comment by Megas97** [comment]
The "Save for all" and "Remove from all" for the PJs is a much needed option imo, wheels would be nice too. here's my suggestion for a new sub-tab next to Colors + Paintjobs one -->
https://community.multitheftauto.com/index.php?p=resources&s=details&id=5645
Ofcourse, the lights would be buyable with GC as everything else, also maybe making it possible for players to upload their own lights style just like with PJs would be really cool :)

**Comment by AleksCore** [comment]
I added button for painjobs, rest I'll do later

**Comment by AleksCore** [comment]
Need to add save for all for neons also
