### ISSUE TITLE
Switching radio stations doesn't display current channel

### ISSUE THREAD

**Issue by JarnoVgr** [MrGreenGaming/MTA-Resources#212]
When switching radio stations the current channel isn't displayed.

**Comment by JarnoVgr** [comment]
Tried to look into this, but I it seems that the radio HUD element is never being hidden.

**Comment by AleksCore** [comment]
We can make our own radio HUD with blackjack and... 
https://wiki.multitheftauto.com/wiki/OnClientPlayerRadioSwitch

**Comment by JarnoVgr** [comment]
It would be fun to show the radio icons in that case, instead of text.

Some inspiration:
http://www.gtagarage.com/mods/show.php?id=24581
http://www.gtagarage.com/mods/show.php?id=11330

**Comment by f1madkiller** [comment]
its tempermental sometimes it works and sometimes it does not
