### ISSUE TITLE
Should players get GC for testing maps?

### ISSUE THREAD

**Issue by AleksCore** [MrGreenGaming/MTA-Resources#213]
When map manager sets a map for tests, GC, tops and some achievements disabled.

I think they should receive GC for finishing such maps.

**Comment by BobT123** [comment]
GC yes TT no imo.

**Comment by Megas97** [comment]
Tops definitely not but I don't see why achievements and GreenCoins are off, we get them for playing/winning so they should be enabled even while test if you ask me.

**Comment by JarnoVgr** [comment]
Maybe just give 1 GC as a good gesture? Combine it with a message like "Thank you for testing this map with us. Here's 1 GC!"

**Comment by Megas97** [comment]
@JarnoVgr that made me laugh a bit :D

**Comment by f1madkiller** [comment]
@JarnoVgr comment of the year goes to you, if that happens will we get GC payment for testing maps?

**Comment by Cena1** [comment]
I personally think GCs shouldn't be disabled (Maybe half the reward), so if 1st players gets 16 GCs and 2nd gets 12 GCs. When testing 1st gets 8 GCs and 2nd gets 6 GCs..etc, but achievements and tops should be tho.

**Comment by AfuSensi** [comment]
@Cena1 done. https://github.com/MrGreenGaming/MTA-Resources/commit/74e69d272179a46ab67d6daeb838117c510ec674
