### ISSUE TITLE
Change soundcloud or add to it Live Radio from real life stations with url

### ISSUE THREAD

**Issue by f1madkiller** [MrGreenGaming/MTA-Resources#230]
Would it be possible to change F7 from soundcloud or add it to play live radio like e.g. http://radioplayer.kissfmuk.com/live/ this radio station if someone has a link they can do it @JarnoVgr @AleksCore @EsDeKa

**Comment by AleksCore** [comment]
@f1madkiller When we talked in-game I thought you meant radio like on ffs server where playlist = songs bought by players :D

You can use /radio or just play it using player/site. Or you want play it for all players?

**Comment by JarnoVgr** [comment]
There's no need to tag us. We'll read it anyways. :)

**Comment by f1madkiller** [comment]
Radio like FFS I think be better now like spend 5 GCs for songs or stuff for all players to hear and press e.g. X to turn it off

**Comment by Megas97** [comment]
ye sounds cool but @AleksCore said "never" when I asked if we'll have ffs radio xd

**Comment by f1madkiller** [comment]
We got better scripters than FFS so I am sure we can do better than there system
