### ISSUE TITLE
Remove time left countdown

### ISSUE THREAD

**Issue by JarnoVgr** [MrGreenGaming/MTA-Resources#243]
Time left countdown should be removed because it's 99% of the time useless. However: It should re-appear in the bottom-right underneath 'Time' when there's less than a minute left.

**Comment by JarnoVgr** [comment]
@AleksCore and @Megas97 : Care to elaborate why you don't like this suggested change?

**Comment by Megas97** [comment]
If you mean the timeleft which is shown at top center of screen I think that players tend to look at it to see if they can finish a map or not. That said, my or anyone else's opinion doesn't matter on the server as I got told recently by the admins on forums so whatever you decide, it's fine.

**Comment by JarnoVgr** [comment]
I want it to appear when it's relevant (e.g. a minute before the timer ends). 90% of the time it's irrelevant, right?

**Comment by JarnoVgr** [comment]
Bump:
[ ] Show map playtime when map is loading.
[ ] Only show timeleft UI element when it's less than 2 minutes.

**Comment by Cena1** [comment]
As @Megas97 said, I myself look at the time to see if I can finish a map or not in case I joined late in an NTS. Also its quite small in the top center of the screen. It doesn't hide anything important or ruin your ingame visibility.
