### ISSUE TITLE
Improve dimensions again

### ISSUE THREAD

**Issue by EsDeKa** [MrGreenGaming/MTA-Resources#247]
Technically it should be possible to disable dimensions clientside for players who prefer cars over fps
Also tweak it a bit, pc's have gotten stronger again since last time it was tweaked

**Comment by Megas97** [comment]
"it should be possible to disable dimensions clientside for players who prefer cars over fps"
How^? I mean, won't that be unfair towards the people who are without dims?
Most won't touch it and will drive alone (won't have traffic) while guys like me will play with everyone else collidable. Explain pls :D

**Comment by JarnoVgr** [comment]
Can we handle the LOD (Level Of Detail) of vehicles? If there's low FPS we should just lower the LOD for remote vehicles.
