### ISSUE TITLE
/rules are diffrent too f9 rules

### ISSUE THREAD

**Issue by f1madkiller** [MrGreenGaming/MTA-Resources#255]
if you type /rules they are differnt to F9 (stig wanted me too make this sorry aleks and SDK)

**Comment by JarnoVgr** [comment]
Command can be removed I guess as we have the UI variant for it.

**Comment by Cena1** [comment]
Can't we just edit /rules? Idk where to find the file for /rules tho.

**Comment by Cena1** [comment]
Its fixed.
