### ISSUE TITLE
Floating messages (and not just) don't match.

### ISSUE THREAD

**Issue by Megas97** [MrGreenGaming/MTA-Resources#256]
Since the 'update' of the ghostmode messages there are a few things I'd like to point out, here goes: 
1. New color and style of the ghostmode messages is bad, really bad. Old ones were perfect, with that deep red color and awesome shadow and text. Why'd you even change that?
2. You changed "has finished" to "finished" text but the "has died. Ranked: " message is still same as before. Wouldn't it be better if it's "getPlayerName(source) .. 'died '..rank..''..suffix.." ?
3. Even if you decide to keep these new ghostmode messages (pls don't..) you'd have to edit the dimension messages as well as now they use the old (and amazing) style and color.

**Comment by AleksCore** [comment]
nothing changed for me lol, or I am not noticed

**Comment by Megas97** [comment]
I'll get F12s when i can :P

**Comment by Megas97** [comment]
Here's example. First image is the cool one (from before), second one is the other version.
cool msg : http://i.imgur.com/Fydpdcw.png
shit msg : http://i.imgur.com/5xprsbm.png
And what I mean is that, for example "Disabled ghostmode" shows in the green version from 2nd pic but the "Dimension changed" or "You will join the first dimension in 5 secs" etc texts still use the old style (from first pic, the cool one).
