### ISSUE TITLE
Remove dimensions.

### ISSUE THREAD

**Issue by Megas97** [MrGreenGaming/MTA-Resources#269]
Get rid of the biggest lag maker. It makes everyone around you invisible, you don't know who is where and when you change a dimension the game freezes for minimum 1 second. Try for a week/month without them and see the difference.

**Comment by AleksCore** [comment]
But mta cant handle 40+ vehicles in the same place. Low fps guaranteed,  that's the reason why dimensions was made

**Comment by AleksCore** [comment]
I didn't had any freezes at all btw

**Comment by Megas97** [comment]
When changing dim, it's hell...cars popin' up from nowhere, game has to load around 10 cars at once which makes lag :D

**Comment by Megas97** [comment]
Look at fps and general slowdown when changing https://www.dropbox.com/s/sdw0lnka5gp03jp/fudims.mp4?dl=0

**Comment by f1madkiller** [comment]
I think dims need to be 1 mode for laggers blockers and high pingers and another for everyone else

**Comment by Cena1** [comment]
The current dims are good imo 👍
