### ISSUE TITLE
Users window

### ISSUE THREAD

**Issue by Bierbuikje** [MrGreenGaming/MTA-Resources#302]
Hi all, Culto came with an idea to see the stats of all players (currently not possible) and we talked about it and came with this:

A tab in the sidebar (F1) named 'users' which opens a window where you can see all the stats of the players in Mr.Green, the same stats as in the F10 tab. In this window it is possible to sort the list based on most wins, most greencoins collected, most playing time etcetera. Maybe some sort of rank who is the best player. We also thought about adding a window where you could search for the toptimes on all maps just like http://mrgreengaming.com/mta/toptimes/ but then in the server.

It would be a nice addition I think, and it gives player something to brag about ingame.

**Comment by Megas97** [comment]
Yep, FFS has it and it looks awesome (the stats).

**Comment by Haxardous** [comment]
I think since /leaderboards are there this suggestion somehow is already done. https://mrgreengaming.com/mta/toptimes/ is already updated too.

**Comment by Cena1** [comment]
I agree with @Haxardous . It is done since /leaderboards is added in F1. The rest of the ideas mentioned (most greencoins collected..etc) is already on our list. So I will close this.
