### ISSUE TITLE
GC Rewards upon finishing, inconsistency between Race and Mix

### ISSUE THREAD

**Issue by Bierbuikje** [MrGreenGaming/MTA-Resources#322]
When finishing an NTS map (Mix server) no gc reward is given when there are too few players in the server (less than 5) but when finishing a race map (Race server) it gives the reward regardless of how many players are online. Should this be corrected by applying the minimum player amount to the race server or give finished players in Mix (in the NTS mode) the gc reward?

**Comment by JarnoVgr** [comment]
Make the GC reward dynamic? If there are less than 5 then reduce the amount that can be received. But it should apply to both gamemodes/servers.

**Comment by AfuSensi** [comment]
Dynamic rewards from race are implemented in mix (nts, rtf), minimum players for nts, race and ctf are also removed, but reward is halved when there are less than 5 players.
