### ISSUE TITLE
Laggers on CtF

### ISSUE THREAD

**Issue by f1madkiller** [MrGreenGaming/MTA-Resources#358]
On CTF on mix laggers get put into lagger mode and can drive through everyone and get the flag and win the game might it be worth disabling lagger mode for CTF or making it they can't pick up the flag @Bierbuikje @AleksCore @Cena1 what do you guys think about this idea?

**Comment by AleksCore** [comment]
Maybe disable it for CTF, shouldn't feel too awful to play against a lagger

**Comment by f1madkiller** [comment]
well i reported this issue in 2016 and still nothing been done

**Comment by AleksCore** [comment]
can't think off another solution though

**Comment by AleksCore** [comment]
won't take a lot of time to fix this issue, need only to decide what to do

**Comment by f1madkiller** [comment]
@Bierbuikje this is still a issue mind looking into it?

**Comment by Cena1** [comment]
Laggers can't take the flag and drive through people actually. Being on lagger mode is shit and will just push you away when someone drive against you and you won't have any affect on others trying to push them. Besides, already opened in #423
