### ISSUE TITLE
Change monthly toptimes to toptimes of last 4 weeks/30 days

### ISSUE THREAD

**Issue by JarnoVgr** [MrGreenGaming/MTA-Resources#39]
Title says it all. Why is it monthly and reset it fully? In my opinion it makes more sense

(feel free to let me know what you think about it)

**Comment by EsDeKa** [comment]
The times aren't reset, they are just not shown. People get a reward for all toptimes they have at the end of a month.

The idea was to make a leaderbord for who has the most tops and monthlies but I didn't get to that yet
