### ISSUE TITLE
Minor lagspikes

### ISSUE THREAD

**Issue by Bierbuikje** [MrGreenGaming/MTA-Resources#394]
Minor lagspikes in both servers at certain moments. Best observable in the Mix server.

The lagspikes happen at the following moments:

- A player joining
- A player quitting
- An NTS checkpoint has been reached (NTS gamemode, Mix server)

My guess would be that too much (serverside) events are triggered when these events happen.

**Comment by EsDeKa** [comment]
Should check performace/sql monitor to see what is causing it

Could also be related to SQL, I know in the past the server could hang if a query took to long.
But most if not all SQL queries should be with async callbacks now which should not cause a hang

Ywa did a windows update recently iirc, possibly related as well

Do you know when it started?

**Comment by f1madkiller** [comment]
Mix has been lagging on and off before Ywa did a windows update but seems to get better after GCshop restart and server restart sometimes as well Mr bier and Mr SDK

**Comment by PlatinMTA** [comment]
They happend allways or sometimes? Could it be cuz some big packages are being send throught triggerClietnEvent()

**Comment by AfuSensi** [comment]
> They happend allways or sometimes? Could it be cuz some big packages are being send throught triggerClietnEvent()

The cause of #1 and #3 were (for the most part) caused by dxCreateTexutre(). 
I recently fixed this issue, at the cost of memory usage. 
https://github.com/MrGreenGaming/MTA-Resources/commit/9e1e6a54bb4974346851fd47d4da589044a0c349

**Comment by AfuSensi** [comment]
Another fix in https://github.com/MrGreenGaming/MTA-Resources/commit/1f4146d9bf7583e211cf4748bff31351d4517daa

A memory leak caused a lag spike every 2 seconds if the resource ran for a longer time.
