### ISSUE TITLE
Weird team tags prevent team from being created

### ISSUE THREAD

**Issue by JarnoVgr** [MrGreenGaming/MTA-Resources#408]
Creating a team with a tag like `P // o // M` will prevent a team from being created, while GCs are deducted. MEH

We need to escape stuff like this.

**Comment by Cena1** [comment]
Didn't SDK fix that?

**Comment by JarnoVgr** [comment]
Well it isn't fixed yet, so probably not. PR #393 might fix this though.

**Comment by Cena1** [comment]
Its not a problem anymore.
