### ISSUE TITLE
Laggers ruin CTF experience

### ISSUE THREAD

**Issue by JarnoVgr** [MrGreenGaming/MTA-Resources#423]
> lagers can get the flag and drive through all cars and drop the flag off it is rather annoying when there are 6 cars defending and 1 guy drives through us all and drops the flag off.

**Comment by Cena1** [comment]
Laggers don't go through cars, its the other way around. Players who are not "lagger" can push the lagger player away easily. Good solution for this is to prevent players with the "lagger" tag from taking the flag. @AfuSensi @Mihoje @Haxardous
