### ISSUE TITLE
All AFK Players = Vote Bug (Both Servers)

### ISSUE THREAD

**Issue by Santiii733** [MrGreenGaming/MTA-Resources#424]
There was always this problem if everyone stays afk.

**Comment by f1madkiller** [comment]
Also a further note bier has tried fixing it and to fix it on discord we must restart race resource

**Comment by JarnoVgr** [comment]
Can someone explain what the exact problem is? This issue report doesn't really inform me about what happens and how to reproduce it.

**Comment by JarnoVgr** [comment]
@Mihoje This is a very annoying bug. Would be great if you'd want to look into it. Thanks.

**Comment by Mihoje** [comment]
That's next on my priority list. Will take a look later today.

**Comment by Mihoje** [comment]
https://github.com/MrGreenGaming/MTA-Resources/commit/ff2c922014ee0c304bf0abe23db943b6e818f360

We'll see what happens

**Comment by Mihoje** [comment]
Fixed.
