### ISSUE TITLE
Accepting team invite doesn't change team

### ISSUE THREAD

**Issue by JarnoVgr** [MrGreenGaming/MTA-Resources#434]
Accepting a team invite is probably broken.

> I invite my mate to my clan he write /accept and game write ... accepted your invite but he isn'T in my clan

**Comment by EsDeKa** [comment]
Does it always happen or is it just with certain people/teams?
Got a screenshot of /debugscript 3 with any errors when it happens?

**Comment by EsDeKa** [comment]
@JarnoVgr fixed now, looks like it was because new accounts are not added to the  `mrgreen_gc`.green_coins mysql database anymore
I assume it's something you changed with the new greencoins

**Comment by JarnoVgr** [comment]
@EsDeKa Thank you for looking into this.
I did change the GC system to fully rely on an API instead of the `green_coins` SQL table. The `green_coins` SQL table is obsolete and unused as of now. Thought I fixed all usages.
