### ISSUE TITLE
Map ACL

### ISSUE THREAD

**Issue by EsDeKa** [MrGreenGaming/MTA-Resources#45]
Right now maps can use clientside bindKey to link to serverside commands (eg num pad + to 'like').
This is impossible to block in MTA's ACL, the only way to fix it is with a script container like Kali is working on in #38.

http://mrgreengaming.com/forums/topic/17161-please-stop-creating-maps-with-abusive-bind-to-get-likes/?p=140443

**Comment by JarnoVgr** [comment]
This shouldn't be used/abused indeed.
