### ISSUE TITLE
Make loading of players faster please :)

### ISSUE THREAD

**Issue by Megas97** [MrGreenGaming/MTA-Resources#50]
Title pretty much says it all, a few weeks ago SDK uploaded some fix and loading was super fast but then it got removed. Any chance to see it back again?

**Comment by JarnoVgr** [comment]
I'm curious what this 'magic' speed up consists of.

**Comment by EsDeKa** [comment]
It was just lowering the limit on how long players can load, but it was buggy for some reason so I disabled it again

**Comment by JarnoVgr** [comment]
What was buggy 'bout it?

**Comment by Megas97** [comment]
So what up with this?

**Comment by AleksCore** [comment]
Don't touch this pls :( It's fast enough imo

**Comment by Megas97** [comment]
Um, I don't see why not make it faster if possible but nvm, not a big problem anyways.
