### ISSUE TITLE
Display car name when entering it

### ISSUE THREAD

**Issue by JarnoVgr** [MrGreenGaming/MTA-Resources#63]
Like GTA itself has. Maybe make it more subtle?

**Comment by AleksCore** [comment]
Woah, I like this idea Mr. Ideas Generator

**Comment by PlatinMTA** [comment]
This can be done just using:

`setPlayerHudComponentVisible("vehicle_name", true)`

We could also make something like this:

`function onEnter(thePlayer)
     if thePlayer ~= localPlayer then return end
     addEventHandler("onClientRender", root, drawFunction)
end
addEventHandler("onClientVehicleEnter", root, onEnter)`
