### ISSUE TITLE
Music player

### ISSUE THREAD

**Issue by V4POR97** [MrGreenGaming/MTA-Resources#645]
We had a music player before,but it has been replaced by the VIP menu,and can't access it again.
I would like to listen music again ingame,and I think many players would appreciate it.
It can be YouTube-based,it would be the best,but SoundCloud would be also good.

**Comment by Megas97** [comment]
I think @AfuSensi said that the SoundCloud API key has expired and they don't let users get a new one at the moment. Also Spotify can't work afaik too so a YouTube browser would be the best bet I guess.

**Comment by AfuSensi** [comment]
A YouTube player needs a custom API made to fetch music and make it streamable ingame. I did do some work on it but due to time constraints i did not finish it.
In the future we will most likely have this.
