### ISSUE TITLE
[BUG] Map timer doesn't appear

### ISSUE THREAD

**Issue by Nick026** [MrGreenGaming/MTA-Resources#767]
Map timer doesn't initially appear when a map starts. Only when the time changes to 45 seconds.

**Comment by cbygh** [comment]
Are you sure this is a bug? I think this is intentional. The map time only makes sense when no one finishes, otherwise it will switch to 45 seconds anyways when the first player finishes.

**Comment by Nick026** [comment]
I'm not sure actually. I know by default that the map has a timer of 20 minutes , which gets reduced to 45 seconds once someone finishes. Even when a map has a custom time like 4 minutes the timer doesn't appear until it gets changed once.

So I think this is a bug, but I will do further investigation in it soon
