### ISSUE TITLE
[Enchantment] Remove or delay the abillity to suicide on Shooter

### ISSUE THREAD

**Issue by Micha3lo** [MrGreenGaming/MTA-Resources#773]
Pressing enter to die is an annoying thing on shooter. Sometimes people will simply press enter to prevent getting killed by someone, which doesn't seem to be fair at all. Either remove an abillity to use enter on shooter or make it "hold to suicide" (like in GTA V). I'd consider simply adding a delay to the enter button itself as well.

**Comment by Nick026** [comment]
Disabled suicide in shooter gamemodes [(commit)](https://github.com/MrGreenGaming/MTA-Resources/commit/ce2fe9a3752ed30e459d16c9067fd8236e103912)
