### ISSUE TITLE
Too much files need to download to start playing

### ISSUE THREAD

**Issue by AleksCore** [MrGreenGaming/MTA-Resources#99]
When you connect to the server first time you will download around 53 Mb and this size only will raise and it could easily raise to 100 Mb in future which is a problem.

**Comment by f1madkiller** [comment]
I think it could be done as download first 5 - 10 mb then play whilst you are downloading rest of the stuff that is needed but it might not work thou depending on scripts and stuff that are in use

**Comment by AfuSensi** [comment]
I dont see why it would raise any further. Most of it can be streamed in later i guess. The scripts itself arent big.

**Comment by AleksCore** [comment]
It will raise because we upload more and more horns

**Comment by AfuSensi** [comment]
Oh right, i forgot about that. Still we could stream horns, or let them download after joining.

**Comment by AfuSensi** [comment]
That and race_fix are about the biggest files on the server right?

**Comment by AfuSensi** [comment]
https://github.com/JarnoVgr/Mr.Green-MTA-Resources/commit/7357d916c1f13ab538971c36d7b4aa0d116ececd Thats 13mb less download when joining, we can reduce it more.

**Comment by AleksCore** [comment]
Very nice! It works :)
